### PR TITLE
chore(storybook): Fix toolbar state not updated immediately after an editor state change

### LINKED ISSUE #259: formatting state not being updated as soon as change triggered
## Overview
The formatting state is not being updated as soon as the button is clicked or a keyboard shortcut is used.
For e.g., When I press `Ctrl+B` or click the `B` (for bold) on the Rich Text Editor, it doesn't show it is turned on. The button is highlighted, suggesting turned on, only when I input the next letter from my keyboard.

## Steps to reproduce
1. Run `npm run storybook:start` or navigate to [https://typist.doist.dev/](https://typist.doist.dev/)
2. Navigate to `Rich-text`-> `Default` from the left menu. 
3. Click on `B` or `Ctrl+B`/`Cmd+B` to toggle bold.
4. Observation: The icon is not yet highlighted suggesting to the user that it didn't turn on. On all other major platforms the button turns on the moment the change is triggered.
5. However, the next letter has the updated formatting (in bold) as per expectations.

## Questions
* Is this a design choice by the team? Because this behaviour is different from other major WYSIWYG editors like MS Word, Google Docs, LibreOffice Writer or even web-based editors (eg Froala https://froala.com/wysiwyg-editor/demo/).

If this is something the team is looking forward to, I can help contribute to a fix.

Thanks!

### PR DESCRIPTION
**Pull request by ayushanand18**
## Overview

This PR tries to fix #259 by replacing the eventListener on Storybook.

### Changes Introduced
* `onSelectionUpdate` changed to `onTransation` on `typist editor toolbar decorator`.
    ```javascript
    editor.on('selectionUpdate', handleSelectionUpdate)
    // is changed to
    editor.on('transaction', handleTransactionUpdate)
    ```
Thanks!

## PR Checklist

-   [x] Pull request title follows the [Conventional Commits Specification](https://www.conventionalcommits.org/)
-   [ ] Added/updated unit test cases and/or end-to-end test cases
-   [ ] Added/updated documentation to Storybook or `README.md`

## Test plan
Doesn't change any existing features, just introduces fix for #259.

## Demo

| Before                      | After                      |
| --------------------------- | -------------------------- |
| Keyboard events and editor button clicks did not update the toolbar | Keyboard shortcuts and toolbar clicks correctly re-render editor toolbar.|
| image | image|

### CODE REVIEW

File: stories/typist-editor/decorators/typist-editor-decorator/typist-editor-toolbar.tsx [hunk 1]
```diff
@@ -45,16 +45,16 @@ function TypistEditorToolbar({ editor }: TypistEditorToolbarProps) {
 
     useEffect(
         function initializeEventListeners() {
-            function handleSelectionUpdate() {
+            function handleTransactionUpdate() {
                 // Force a rerender for every selection update in the editor - an event that ocurrs
                 // outside of the React lifecycle - to update the toolbar buttons `pressed` state
```
Comment (rfgamaral) [inline stories/typist-editor/decorators/typist-editor-decorator/typist-editor-toolbar.tsx:50]:
```suggestion
                // Force a rerender for every transaction in the editor - an event that ocurrs
                // outside of the React lifecycle - to update the toolbar buttons `pressed` state
```

**Review by rfgamaral — CHANGES_REQUESTED** [review]
Thank you for fixing this @ayushanand18 🤗

It works as expected, but it's just missing a small change in the comment to match the `selectionUpdate` to `transaction` change. I'll merge it afterwards :)

**Comment by rfgamaral** [comment]
@ayushanand18 FYI, I changed the PR title from `fix` to `chore` because `fix` would publish a new version (which we don't need for this one), removed the issue number from the title (which is added automatically to the commit message once the PR is merged), and also re-worded the commit message a bit to make it more clear what it's actually doing.

**Review by rfgamaral — APPROVED** [review]

**Comment by ayushanand18** [comment]
> FYI, I changed the PR title from `fix` to `chore` because `fix` would publish a new version [...], removed the issue number from the title [...], and also re-worded the commit message a bit [...]

Thanks a lot @rfgamaral! I'll make sure to follow those guidelines for any future contributions.
